-- AlterTable
ALTER TABLE "Item" ALTER COLUMN "image" SET DEFAULT '',
ALTER COLUMN "image" SET DATA TYPE TEXT;

-- AlterTable
ALTER TABLE "Storage" ALTER COLUMN "image" SET DEFAULT '',
ALTER COLUMN "image" SET DATA TYPE TEXT;
